<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="64" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
      <class name="ExerciseOne.ExerciseOneTest">
        <test-method status="PASS" signature="testIsCorrectTAN()[pri:0, instance:ExerciseOne.ExerciseOneTest@72b6cbcc]" name="testIsCorrectTAN" duration-ms="9" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsCorrectTAN -->
        <test-method status="PASS" signature="testIsValidCity()[pri:0, instance:ExerciseOne.ExerciseOneTest@72b6cbcc]" name="testIsValidCity" duration-ms="1" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsValidCity -->
        <test-method status="PASS" signature="testIsValidNOT()[pri:0, instance:ExerciseOne.ExerciseOneTest@72b6cbcc]" name="testIsValidNOT" duration-ms="1" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsValidNOT -->
        <test-method status="PASS" signature="testIsValidPI()[pri:0, instance:ExerciseOne.ExerciseOneTest@72b6cbcc]" name="testIsValidPI" duration-ms="1" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsValidPI -->
        <test-method status="FAIL" signature="testIsValidRI()[pri:0, instance:ExerciseOne.ExerciseOneTest@72b6cbcc]" name="testIsValidRI" duration-ms="2" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotSame(Assert.java:1033)
at org.testng.Assert.assertNull(Assert.java:965)
at org.testng.Assert.assertNull(Assert.java:953)
at ExerciseOne.ExerciseOneTest.testIsValidRI(ExerciseOneTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsValidRI -->
        <test-method status="PASS" signature="testIsValidTAN()[pri:0, instance:ExerciseOne.ExerciseOneTest@72b6cbcc]" name="testIsValidTAN" duration-ms="2" started-at="2022-01-24T17:04:38 EST" finished-at="2022-01-24T17:04:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsValidTAN -->
      </class> <!-- ExerciseOne.ExerciseOneTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
